version: "3.9"
services:
  invoicesystem.api:
    image: ${DOCKER_REGISTRY-}invoicesystemapi
    container_name: InvoiceSystem.Api
    build:
      context: .
      dockerfile: InvoiceSystem.Api/Dockerfile
    ports:
      - "5000:8080"
      - "5001:8081"
    depends_on:
      - impact.database
    networks:
      - custom_network

  impact.database:
    image: postgres:latest
    container_name: Impact.Database
    environment:
      POSTGRES_DB: impact
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./.containers/db:/var/lib/postgresql/data
    ports:
      - "8888:5432"
    restart: always
    networks:
     - custom_network
       
volumes:
  postgres_data:
    
networks:
  custom_network:
   driver: bridge