# This is a generated file. Not intended for manual editing.
version: "3.8"
services:
  invoicesystem.api:
    build:
      context: "C:\\Users\\valk\\source\\repos\\InvoiceSystem"
      dockerfile: "InvoiceSystem.Api/Dockerfile"
      target: "base"
      args:
        BUILD_CONFIGURATION: "Debug"
    command: []
    entrypoint:
    - "/opt/JetBrains/RiderDebuggerTools/linux-x64/JetBrains.Debugger.Worker"
    - "--runtimeconfig"
    - "/opt/JetBrains/RiderDebuggerTools/JetBrains.Debugger.Worker.runtimeconfig.json"
    - "--mode=server"
    - "--frontend-port=57000"
    - "--backend-port=57200"
    - "--roslyn-worker-port=57400"
    - "--timeout=60"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
      RIDER_DEBUGGER_LOG_DIR: "/var/opt/JetBrains/RiderDebuggerTools"
      RESHARPER_LOG_CONF: "/etc/opt/JetBrains/RiderDebuggerTools/backend-log.xml"
    image: "invoicesystemapi:dev"
    ports:
    - "127.0.0.1:57002:57000"
    - "127.0.0.1:57202:57200"
    - "127.0.0.1:57402:57400"
    volumes:
    - "C:\\Users\\valk\\source\\repos\\InvoiceSystem\\InvoiceSystem.Api:/app:rw"
    - "C:\\Users\\valk\\source\\repos\\InvoiceSystem:/src:rw"
    - "C:\\Users\\valk\\AppData\\Roaming\\Microsoft\\UserSecrets:/home/app/.microsoft/usersecrets"
    - "C:\\Users\\valk\\.nuget\\packages:/home/app/.nuget/packages"
    - "C:\\Users\\valk\\AppData\\Local\\JetBrains\\RiderRemoteDebugger\\2024.3.5\\\
      Linux64:/opt/JetBrains/RiderDebuggerTools"
    - "C:\\Users\\valk\\AppData\\Local\\Programs\\Rider\\bin\\backend-log.xml:/etc/opt/JetBrains/RiderDebuggerTools/backend-log.xml"
    - "C:\\Users\\valk\\AppData\\Local\\JetBrains\\Rider2024.3\\log\\DebuggerWorker\\\
      JetBrains.Debugger.Worker.2025_2_21_21_12_36:/var/opt/JetBrains/RiderDebuggerTools:rw"
    working_dir: "/app"
